title: test
author:
  name: Parker Addison
  email:
description: >

repository: https://github.com/parkeraddison/parkeraddison.github.io

theme: parkeraddison

parkeraddison:
  nav_links:
    - name: Portfolio
      url: /portfolio
    - name: Blog
      url: /blog
    - name: Resume
      url: /resume
    - name: Contact
      url: /contact

collections:
  blog:
    output: true
  news:
  projects:

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

kramdown:

plugins:
  - jekyll-feed
  - jekyll-seo-tag
