baseURL: "https://parkeraddison.com/"
languageCode: "en-us"
title: "Parker Addison"

enableRobotsTXT: true
canonifyURLs: true
pluralizeListTitles: false

Author:
    name: "Parker Grey Addison"

params:
    resumeURL: "https://nbviewer.jupyter.org/github/parkeraddison/resume/blob/master/resume.pdf"

disableKinds:
    - "projects"

# taxonomies:
#     tag: tags

markup:
    defaultMarkdownHandler: pandoc

assetDir: assets
publishDir: "../"
