baseURL: "https://parkeraddison.com/"
languageCode: "en-us"
title: "Parker Addison"

enableRobotsTXT: true
canonifyURLs: true
pluralizeListTitles: false

Author:
    name: "Parker Grey Addison"

params:
    resumeURL: "https://nbviewer.jupyter.org/github/parkeraddison/resume/blob/master/resume.pdf"

disableKinds:
    - "taxonomy"
    - "taxonomyTerm"

# taxonomies:
#     tag: tags

markup:
    # defaultMarkdownHandler: pandoc
    defaultMarkdownHandler: goldmark
    goldmark:
        renderer:
            unsafe: true
    highlight:
        style: monokai

assetDir: assets
publishDir: "../"
